### ISSUE TITLE
Send to Unreal is broken in Blender 4.0 beta, FBX is corrupted/Missing data

### ISSUE THREAD

**Issue by funkysandwich** [EpicGamesExt/BlenderTools#676]
Hi. Upon using Push Assets in Blender 4.0 beta, the assets fail to be imported by Unreal, but in Blender 3.6 it works fine.
An export using Blender's built in FBX exporter in 4.0 does import. Just not ones from Push Assets.

Snippet from Unreal output log on import
```
LogFactory: FactoryCreateFile: StaticMesh with FbxFactory (0 0 C:/Users/funky/AppData/Local/Temp/blender/send2ue/data/StaticMesh/Blender40ExportTest.fbx)
LogFbx: Loading FBX Scene from C:/Users/funky/AppData/Local/Temp/blender/send2ue/data/StaticMesh/Blender40ExportTest.fbx
FBXImport: Warning: FBX Scene Loading Failed : 'File is corrupted Blender40ExportTest.fbx' 
FBXImport: Warning: Can't detect import type. No mesh is found or animation track. 
LogAssetTools: Warning: Failed to import 'C:/Users/funky/AppData/Local/Temp/blender/send2ue/data/StaticMesh/Blender40ExportTest.fbx'. Failed to create asset '/Game/UNSORTED/Blender40ExportTest'.
```

Tested with Blender 4.0.0 Beta, and Send to Unreal 2.4.2

**Comment by bruteforks** [comment]
Fix worked perfectly. Thank you! 

Attaching this because I thought someone would have posted a fixed version in comments, but I didn't see one. Enjoy

[send2ue_2.4.3_editedwithfix.zip](https://github.com/EpicGamesExt/BlenderTools/files/14451541/send2ue_2.4.3_editedwithfix.zip)

**Comment by WindMill90** [comment]
Okay the fix works in 4.1 alpha but not on 4.1 beta( throws errror I posted above) .. Still in 4.1 alpha exporting skeletal mesh works fine but exporting animation resulted in the following error..

Python: Traceback (most recent call last):
  File "C:\Users\****\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\operators.py", line 71, in modal
    raise error
  File "C:\Users\****\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\operators.py", line 61, in modal
    function(*args, **kwargs)
  File "C:\Users\****\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\export.py", line 265, in export_animation
    export_file(properties)
  File "C:\Users\****\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\export.py", line 166, in export_file
    export_fbx_file(file_path, export_settings)
  File "C:\Users\****\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\export.py", line 83, in export_fbx_file
    io.fbx.export(
  File "C:\Users\****\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\io\fbx.py", line 552, in export
    export_fbx_bin.save(self, bpy.context, **keywords)
  File "D:\Blender Versions\blender-4.1.0-alpha+main.2b0448c91d7a-windows.amd64-release\4.1\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3628, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "D:\Blender Versions\blender-4.1.0-alpha+main.2b0448c91d7a-windows.amd64-release\4.1\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3496, in save_single
    scene_data = fbx_data_from_scene(scene, depsgraph, settings)
  File "D:\Blender Versions\blender-4.1.0-alpha+main.2b0448c91d7a-windows.amd64-release\4.1\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 2867, in fbx_data_from_scene
    animations, animated, frame_start, frame_end = fbx_animations(tmp_scdata)
  File "D:\Blender Versions\blender-4.1.0-alpha+main.2b0448c91d7a-windows.amd64-release\4.1\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 2455, in fbx_animations
    fbx_animations_do(scene_data, strip, strip.frame_start, strip.frame_end, True, force_keep=True))
  File "C:\Users\****\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\io\fbx.py", line 160, in fbx_animations_do
    anim_loc.add_keyframe(real_currframe, loc * location_multiple)
AttributeError: 'AnimationCurveNodeWrapper' object has no attribute 'add_keyframe'. Did you mean: 'set_keyframes'?

**Comment by maronh** [comment]
> Fix worked perfectly. Thank you!
> 
> Attaching this because I thought someone would have posted a fixed version in comments, but I didn't see one. Enjoy
> 
> [send2ue_2.4.3_editedwithfix.zip](https://github.com/EpicGamesExt/BlenderTools/files/14451541/send2ue_2.4.3_editedwithfix.zip)

Thank you! I had no idea what to do lol

**Comment by alexwhitlam** [comment]
Hi... where can I find the documentation for these tools? Link dead.

**Comment by Kingfelix23** [comment]
Dunno what happened to all the links, hopefully temporarily bug, but videos are still up:

**Comment by alexisrivera3d** [comment]
> Fix worked perfectly. Thank you!
> 
> Attaching this because I thought someone would have posted a fixed version in comments, but I didn't see one. Enjoy
> 
> [send2ue_2.4.3_editedwithfix.zip](https://github.com/EpicGamesExt/BlenderTools/files/14451541/send2ue_2.4.3_editedwithfix.zip)

Working on Blender 4.0.1, thank you!

**Comment by MalikuMane** [comment]
> Okay the fix works in 4.1 alpha but not on 4.1 beta( throws errror I posted above) .. Still in 4.1 alpha exporting skeletal mesh works fine but exporting animation resulted in the following error..
> 
> Python: Traceback (most recent call last): File "C:\Users*_**\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\operators.py", line 71, in modal raise error File "C:\Users***_\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\operators.py", line 61, in modal function(_args, **kwargs) File "C:\Users***_\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\export.py", line 265, in export_animation export_file(properties) File "C:\Users*_**\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\export.py", line 166, in export_file export_fbx_file(file_path, export_settings) File "C:\Users***_\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\export.py", line 83, in export_fbx_file io.fbx.export( File "C:\Users****\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\io\fbx.py", line 552, in export export_fbx_bin.save(self, bpy.context, *_keywords) File "D:\Blender Versions\blender-4.1.0-alpha+main.2b0448c91d7a-windows.amd64-release\4.1\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3628, in save ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod) File "D:\Blender Versions\blender-4.1.0-alpha+main.2b0448c91d7a-windows.amd64-release\4.1\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3496, in save_single scene_data = fbx_data_from_scene(scene, depsgraph, settings) File "D:\Blender Versions\blender-4.1.0-alpha+main.2b0448c91d7a-windows.amd64-release\4.1\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 2867, in fbx_data_from_scene animations, animated, frame_start, frame_end = fbx_animations(tmp_scdata) File "D:\Blender Versions\blender-4.1.0-alpha+main.2b0448c91d7a-windows.amd64-release\4.1\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 2455, in fbx_animations fbx_animations_do(scene_data, strip, strip.frame_start, strip.frame_end, True, force_keep=True)) File "C:\Users***_\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\io\fbx.py", line 160, in fbx_animations_do anim_loc.add_keyframe(real_currframe, loc * location_multiple) AttributeError: 'AnimationCurveNodeWrapper' object has no attribute 'add_keyframe'. Did you mean: 'set_keyframes'?

Also seeing this error on 4.0.2 exporting animations with the mentioned fix.

**Comment by akomili** [comment]
> Trid this and got the following error..
> 
> (just the last few lines of error)
> 
> File "D:\Blender Versions\blender-4.1.0-beta+v41.c6e229d3e470-windows.amd64-release\blender-4.1.0-beta+v41.c6e229d3e470-windows.amd64-release\4.1\python\Lib\re_parser.py", line 850, in _parse
> 
> raise source.error('global flags not at the start '
> 
> re.error: global flags not at the start of the expression at position 19

@WindMill90 did you ever find a fix for this one? I get the same using Blender 4.1.1 and Unreal 5.4

**Comment by JoshQuake** [comment]
@akomili This fork is dead. [Here's the up to date fork](https://github.com/poly-hammer/BlenderTools)

**Comment by Kingfelix23** [comment]
> @akomili This fork is dead. [Here's the up to date fork](https://github.com/poly-hammer/BlenderTools)

What does that mean? Did Epic abandon it? Is there any other changes besides fixing the line of code that stopped it from working?

**Comment by JoshQuake** [comment]
@Kingfelix23 Yep Epic switched the license to MIT at the beginning of this year and abandoned the project, So we (Polyhammer and myself) have taken the mantle in maintaining it.

There are a lot of fixes and some new features for both Send to Unreal and UE to Rigify.

**Comment by Kingfelix23** [comment]
> @Kingfelix23 Yep Epic switched the license to MIT at the beginning of this year and abandoned the project, So we (Polyhammer and myself) have taken the mantle in maintaining it.
> 
> There are a lot of fixes and some new features for both Send to Unreal and UE to Rigify.

Sounds great. Thanks for that!
